// contractions.js
export const contractionsList = [
    "aren't",
    "can't",
    "couldn't",
    "didn't",
    "doesn't",
    "don't",
    "hadn't",
    "hasn't",
    "haven't",
    "he'd",
    "he'll",
    "he's",
    "I'll",
    "I'm",
    "I've",
    "isn't",
    "it'd",
    "it'll",
    "it's",
    "let's",
    "mightn't",
    "mustn't",
    "she'd",
    "she'll",
    "she's",
    "shouldn't",
    "that's",
    "they'll",
    "they're",
    "they've",
    "wasn't",
    "we'll",
    "we're",
    "weren't",
    "we've",
    "won't",
    "wouldn't",
    "you'll",
    "you're",
    "you've",
  ];
  
  export default contractionsList;